### ISSUE TITLE
Remove name in Langauage status bar

### ISSUE THREAD

**Issue by damassi** [subtleGradient/language-javascript#2]
I know this is pretty nitpicky, and people like credit, but seeing "Javascript by SubtleGradient" in my status bar is super annoying.  Is it possible to change that to something more subtle like "Javascript+"?  It also takes up a ton of space.  

![screen shot 2015-06-26 at 2 29 24 pm](https://cloud.githubusercontent.com/assets/236943/8387717/c77b5cc6-1c0f-11e5-9b91-857ae7b2123a.png)

**Comment by subtleGradient** [comment]
I'm open to suggestions. I had to keep the name unique so you know what you've got selected. Ideally there would be a separate short label I could define so it's less obnoxious. Sorry about that

**Comment by damassi** [comment]
Since you're covering all the bases (React, ES6/7, etc) how about JavaScriptNext?  Or JavaScriptHarmony?  Understandably both those terms seem a bit dated, but they do seem appropriate.

**Comment by subtleGradient** [comment]
Most of the time you'll have JavaScript with jsx enabled. JavaScript by
SubtleGradient doesn't support all the fancy new stuff. Unless I screwed
something up

**Comment by damassi** [comment]
Oh my!  I'm so sorry, this is the package I meant to comment on which is the only Atom package that fully parses all of the new JS syntax correctly:  

https://github.com/subtlegradient/language-javascript-jsx

**Comment by damassi** [comment]
I moved the issue over
